FactoryBot.define do
    factory :alert do
        message { "Test alert message generated by FactoryBot." }
        origin { :ml_detection }
        status { :pending }
        via_email { false }
    end
end
