version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: fire_alarm_development 
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    command: --default-authentication-plugin=mysql_native_password 
  redis:
    image: redis:7.2-alpine
    container_name: fire_alarm_redis
    restart: always
    ports:
      - "6379:6379" 
    volumes:
      - redis_data:/data
  api: 
    build:
      context: . 
      dockerfile: Dockerfile
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b 0.0.0.0"
    volumes:
      - .:/app 
    ports:
      - "3000:3000"
      - "8000:8000"
    depends_on:
      - db
      - redis
    env_file:
      - ./.env.docker
  sidekiq:
    build:
      context: .
      dockerfile: Dockerfile
    command: bundle exec sidekiq
    volumes:
      - .:/app
    depends_on:
      - db
      - redis
    env_file:
      - ./.env.docker
  client:
    build:
      context: ./nuxt-client
      dockerfile: Dockerfile
    container_name: fire_alarm_client_nuxt
    ports:
      - "8080:3000" 
    volumes:
      - ./nuxt-client:/app 
      - /app/node_modules 
    environment:
      - NUXT_PUBLIC_API_BASE=http://localhost:3000/api/v1 
    depends_on:
      - api
  ai_service:
    build:
      context: ./fire-detection-ai-service 
      dockerfile: Dockerfile
    container_name: fire_ai_service
    ports:
      - "5001:5001" 
    environment:
      - PORT=5001
    restart: unless-stopped
volumes:
  db_data:
  redis_data:
