scan_cameras_job:
  cron: "*/120 * * * *"
  class: "Detections::ProcessAllCamerasJob"
  queue: "default"

weather_api_simulation:
  cron: "*/120 * * * *"
  class: "SensorLogs::WeatherApiSimulationJob"
  queue: "default"
